In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df=pd.read_csv(r"C:\Users\icon\Desktop\ML\train.csv")

In [4]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [5]:
data=pd.read_csv(r"C:\Users\icon\Desktop\ML\train.csv")

In [6]:
df['SibSp'].unique()

array([1, 0, 3, 4, 2, 5, 8], dtype=int64)

In [7]:
df.describe(include='all')

PassengerId    Survived      Pclass                     Name   Sex  \
count    891.000000  891.000000  891.000000                      891   891   
unique          NaN         NaN         NaN                      891     2   
top             NaN         NaN         NaN  Braund, Mr. Owen Harris  male   
freq            NaN         NaN         NaN                        1   577   
mean     446.000000    0.383838    2.308642                      NaN   NaN   
std      257.353842    0.486592    0.836071                      NaN   NaN   
min        1.000000    0.000000    1.000000                      NaN   NaN   
25%      223.500000    0.000000    2.000000                      NaN   NaN   
50%      446.000000    0.000000    3.000000                      NaN   NaN   
75%      668.500000    1.000000    3.000000                      NaN   NaN   
max      891.000000    1.000000    3.000000                      NaN   NaN   

               Age       SibSp       Parch  Ticket        Fare    Cabin  \
count   714.000000  891.000000  891.000000     891  891.000000      204   
unique         NaN         NaN         NaN     681         NaN      147   
top            NaN         NaN         NaN  347082         NaN  B96 B98   
freq           NaN         NaN         NaN       7         NaN        4   
mean     29.699118    0.523008    0.381594     NaN   32.204208      NaN   
std      14.526497    1.102743    0.806057     NaN   49.693429      NaN   
min       0.420000    0.000000    0.000000     NaN    0.000000      NaN   
25%      20.125000    0.000000    0.000000     NaN    7.910400      NaN   
50%      28.000000    0.000000    0.000000     NaN   14.454200      NaN   
75%      38.000000    1.000000    0.000000     NaN   31.000000      NaN   
max      80.000000    8.000000    6.000000     NaN  512.329200      NaN   

       Embarked  
count       889  
unique        3  
top           S  
freq        644  
mean        NaN  
std         NaN  
min         NaN  
25%         NaN  
50%         NaN  
75%         NaN  
max         NaN

In [ ]:
#df_year = df[['numcol','totalprod','year','yieldpercol','stocks','prodvalue']].groupby('year').sum()
#.groupby("year").sum()
#df_year.head()

In [ ]:
sns.barplot(x='Sex', y='Survived',data=df)
print('Percentage of females who survived: ', df['Survived'][df['Sex']=='female'].value_counts())
print('Percentage of males who survived: ', df['Survived'][df['Sex']=='male'].value_counts())
plt.title('Percentage of Survived Males and Females',fontsize =10)

In [ ]:
sns.barplot(x='Pclass', y='Survived',data=df)
print('Percentage of females who survived: ', df['Survived'][df['Sex']=='female'].value_counts())
print('Percentage of males who survived: ', df['Survived'][df['Sex']=='male'].value_counts())
plt.title('Percentage of Survived and dead Males and Females',fontsize =10)

In [ ]:
#Passengers of class 1 Survived the most and of class 3 died the most

In [ ]:
sns.barplot(x='SibSp', y='Survived',data=df)
print('Percentage of females who survived: ', df['Survived'][df['Sex']=='female'].value_counts())
print('Percentage of males who survived: ', df['Survived'][df['Sex']=='male'].value_counts())
plt.title('Graph of Siblings and Survived and dead Males and Females',fontsize =10)

SyntaxError: invalid syntax (590923873.py, line 1)

In [ ]:
plt.figure(figsize=(25,8))
plt.plot(df['SibSp'],df['Survived'],color='green', marker='o', linestyle='dashed',markerfacecolor='red')
plt.title('Graph of Siblings and Survived and dead Males and Females',fontsize =10)
plt.xlabel('SibSp',fontsize=25)
plt.ylabel('Survived',fontsize = 25)

In [ ]:
plt.figure(figsize=(25,8))
plt.plot(df['Pclass'],df['Survived'],color='green', marker='o', linestyle='dashed',markerfacecolor='red')
plt.title('Graph of Siblings and Survived and dead Males and Females',fontsize =10)
plt.xlabel('Pclass',fontsize=25)
plt.ylabel('Survived',fontsize = 25)

In [ ]:
plt.figure(figsize=(25,8))
plt.plot(df['Sex'],df['Survived'],color='green', marker='o', linestyle='dashed',markerfacecolor='red')
plt.title('Graph of Siblings and Survived and dead Males and Females',fontsize =10)
plt.xlabel('Sex',fontsize=25)
plt.ylabel('Survived',fontsize = 25)

In [ ]:
#from sklearn.linear_model import LogisticRegression


In [8]:
df=df.dropna()

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [10]:
df=df.drop(['Embarked','Name','Cabin','Ticket'], axis = 1)

In [11]:
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})

In [15]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(['Survived', 'Sex'],axis=1), 
                                                    df['Survived'], test_size=0.20, 
                                                    random_state=8)

In [16]:
logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)

LogisticRegression()

In [19]:
predictions = logmodel.predict(X_test)
X_test.head()

PassengerId  Pclass   Age  SibSp  Parch      Fare
809          810       1  33.0      1      0   53.1000
137          138       1  37.0      1      0   53.1000
496          497       1  54.0      1      0   78.2667
659          660       1  58.0      0      2  113.2750
3              4       1  35.0      1      0   53.1000

In [24]:
accuracy=logmodel.score(X_test,y_test)
print(accuracy*100,'%')

62.16216216216216 %


In [25]:
predictions

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0], dtype=int64)

In [28]:
from sklearn.metrics import classification_report
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.57      0.27      0.36        15
           1       0.63      0.86      0.73        22

    accuracy                           0.62        37
   macro avg       0.60      0.57      0.55        37
weighted avg       0.61      0.62      0.58        37



In [30]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,predictions)

array([[ 4, 11],
       [ 3, 19]], dtype=int64)